# Generated by Django 3.0.8 on 2020-10-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rubber_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
